import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { createContext, useState } from "react";
import { AvatarMenuData } from "../src/AvatarMenuData";

export const ItemData = createContext();

export default function Home(active) {
  const [activeTab, setActiveTab] = useState(active);
  const [clickItem, setClickItem] = useState({
    face: "aaa",
    hair: "aaa",
    eyebrows: "aaa",
    eyes: "aaaa",
    nose: "aaa",
    mouth: "aaa",
  });

  const value = {
    clickItem,
    setClickItem,
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* アバター画像 */}
      <div>{clickItem.face}</div>
      <div>{clickItem.hair}</div>
      {/* アバターメニュー */}
      <ul className="AvatarMenu">
        {AvatarMenuData.map((tab, id) => {
          return (
            <li className="navItem" key={tab}>
              <div onClick={() => setActiveTab(id)} className={`navLink ${id === activeTab ? "active" : ""}`} href="#">
                {tab.icon}
              </div>
            </li>
          );
        })}
      </ul>
      <div className="tabContent">
        <div className="tabItem">
          {AvatarMenuData.map(({ id, contents }) => {
            return (
              <div className="tabItemInner" key={contents}>
                {/* アバターリスト */}
                <ItemData.Provider value={value}>{activeTab === id ? contents : ""}</ItemData.Provider>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
